import { describe, it, expect,vi,beforeEach } from "vitest";
import { NextRequest } from "next/server";
import {POST} from './route'
import { generateResponse } from "../../lib/ai";
import { getOrCreateChat } from "@/app/lib/chatIdCreation";
import { saveMessage } from "@/app/lib/messages";


vi.mock('../../lib/ai', () => ({
      generateResponse: vi.fn(),
  }))
    
vi.mock('@/app/lib/chatIdCreation', () => ({
  getOrCreateChat: vi.fn(),
  }))
  
vi.mock('@/app/lib/messages', () => ({
    saveMessage:vi.fn(),
}))

function createfakeStrem(text: string) {
  const encoder = new TextEncoder();

  return new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(encoder.encode(text))
      controller.close();
    }
  })
  
}
describe('Message Test Scenarios ', () => {
  beforeEach(() =>
  {
     vi.resetAllMocks();
  })

    it.each([
      ["empty", ""],
      ["whitespacee-only", "  "],
      ["number", 123],
      ["boolean", true],
      ["object", {}],
      ["array", []],
      ["null", null],
    ])("reject a Invaild message", async(description,invalidMessage) => {
      const request = new NextRequest("http://localhost/api/message", {
        method: "POST",
        headers: {
          "Content-type":"application/json"
        },
        body: JSON.stringify({
          message:invalidMessage
        }) 

      })
      const response = await POST(request);
      const result = await response.json();

      expect(response.status).toBe(400);
      expect(result.error).toBe("Message is required");
      
    })
    
    it("Valid anonymous message", async() => {

      const fakeStream = createfakeStrem("AI Response");


    // const mockResponse = vi.fn((message: string) => `response generated by AI`);
  vi.mocked(generateResponse).mockResolvedValue(fakeStream);

    const request = new NextRequest("http://localhost/api/message", 
      {
        method: 'POST',
        headers: {
          "Content-type": "application/json"
        },
        body: JSON.stringify({
          message:"Hello AI"
        })
      }
    )
      const response = await POST(request);

      const result = await response.text();


      expect(result).toBe("AI Response")
      expect(response.status).toBe(200);
      expect(getOrCreateChat).not.toHaveBeenCalled();
      expect(saveMessage).not.toHaveBeenCalled();
      expect(response.headers.get("x-chat-id")).toBe("");
      expect(generateResponse).toHaveBeenCalledWith("Hello AI");
    })
    

  
  
  it("accepts a message for a logged-in user with an existing chat", async () => {
    
    const fakeStream = createfakeStrem("AI Response");
    
    vi.mocked(generateResponse).mockResolvedValue(fakeStream);

   vi.mocked(getOrCreateChat).mockResolvedValue("chat-1234");
    const request = new NextRequest("http://localhost/api/message", {
      method: 'POST',
      headers: {
        "Content-type": "application/json",
        "x-user-id": "user-1234",
      },
      body: JSON.stringify({
        message: "HELLO AI",
        chatId: "chat-1234"

      })
    })

    const response = await POST(request);
    const result = await response.text();

    expect(result).toBe("AI Response");
    expect(response.status).toBe(200);

    expect(getOrCreateChat).toHaveBeenCalledWith(
      "chat-1234",
      "user-1234"
    )
    expect(saveMessage).toHaveBeenCalledWith({
      chatId: "chat-1234",
      content: "HELLO AI",
      role:'user'
    })
    expect(generateResponse).toHaveBeenCalledWith("HELLO AI")
  })

  it("creates a new chat for a logged-in user when chatId is missing", async () => {
    
    const fakeStream = createfakeStrem("AI RESPONSE")

    vi.mocked(getOrCreateChat).mockResolvedValue("new-chat-1234");

    vi.mocked(generateResponse).mockResolvedValue(fakeStream);
    
    const request = new NextRequest("http://localhost/api/message", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-user-id":"user-1234"
      },
      body: JSON.stringify({
        message: "HELLO AI",
      })
    })

    const response = await POST(request);
    const result = await response.text();

    expect(result).toBe("AI RESPONSE");
    expect(response.status).toBe(200);

    expect(getOrCreateChat).toHaveBeenCalledWith(
      undefined,
      "user-1234"
    )

    expect(saveMessage).toHaveBeenCalledWith({
      chatId: "new-chat-1234",
        content: "HELLO AI",
        role: "user",
    })
    expect(response.headers.get("x-chat-id")).toBe("new-chat-1234");
   
  })

  it('AI failed to response',async() => {
    
    vi.mocked(generateResponse).mockRejectedValueOnce(
      new Error("AI service unavailable")
    )

    const request = new NextRequest("http://localhost/api/message", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-user-id":"user-1234"
      },
      body: JSON.stringify({
        message: "HELLO AI",
         chatId: "chat-1234"
      })
    })
    const response = await POST(request);
  const result = await response.json();
  expect(response.status).toBe(500);
    expect(result).toEqual({
      error: "Failed to process chat",
    })
  expect(generateResponse).toHaveBeenCalled();

  })
    
  })
